apiVersion: v2
appVersion: 12.2.0
description: A Helm chart for Kubernetes
name: valtimo-backend
type: application
version: 3.0.0

dependencies:
  - name: postgresql
    version: ~12.5.6
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - postgresql
  - name: mysql
    version: ~9.10.1
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - mysql
  - name: keycloak
    version: ~15.1.2
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - keycloak
